#!/usr/bin/env python3
"""
meta.meta_enum 테이블에서 enum 값을 읽어 프론트엔드 TypeScript 파일을 생성한다.

사용법:
    ./venv/bin/python scripts/generate_frontend_enums.py

출력:
    workspace/frontend/packages/domain/src/__generated__/enums.ts

설계 의도:
    - DB(main.meta_enum)를 단일 진실 공급원(Single Source of Truth)으로 사용
    - 생성된 TypeScript 파일은 프론트엔드에서 직접 import하여 사용
    - as const 객체 + type export 패턴으로 타입 안전성 보장
    - CI/CD 파이프라인에서 DB 마이그레이션 후 자동 실행 가능
"""
from __future__ import annotations

import os
import sys
from datetime import datetime
from typing import Any

# 프로젝트 루트를 PYTHONPATH에 추가
_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _PROJECT_ROOT)

from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session, sessionmaker

from app.core.config import settings

# ---------------------------------------------------------------------------
# 1. DB 연결
# ---------------------------------------------------------------------------
engine = create_engine(
    settings.SQLALCHEMY_DATABASE_URI,
    echo=False,
    pool_pre_ping=True,
)

SessionLocal = sessionmaker(
    bind=engine,
    autoflush=False,
    autocommit=False,
    expire_on_commit=False,
    class_=Session,
)


# ---------------------------------------------------------------------------
# 2. 데이터 조회
# ---------------------------------------------------------------------------
def fetch_enums(session: Session) -> list[dict[str, Any]]:
    """meta.meta_enum 테이블에서 모든 enum 값을 조회한다."""
    rows = session.execute(
        text(
            "SELECT enum_type, enum_value, description "
            "FROM meta.meta_enum "
            "ORDER BY enum_type, enum_value"
        )
    ).fetchall()
    return [{"enum_type": r[0], "enum_value": r[1], "description": r[2]} for r in rows]


# ---------------------------------------------------------------------------
# 3. TypeScript 코드 생성
# ---------------------------------------------------------------------------
def _to_ts_constant_name(enum_value: str) -> str:
    """DB enum_value를 TypeScript 상수명으로 변환한다.
    
    예: "PAYMENT_PENDING" → "PAYMENT_PENDING" (그대로 사용)
    """
    return enum_value


def _to_ts_type_name(enum_type: str) -> str:
    """DB enum_type을 TypeScript 타입명으로 변환한다.
    
    예: "order_status" → "OrderStatus"
    """
    return "".join(word.capitalize() for word in enum_type.split("_"))


def generate_ts(enums: list[dict[str, Any]]) -> str:
    """enum 데이터로 TypeScript 파일 내용을 생성한다."""
    lines: list[str] = []
    
    # 파일 헤더
    lines.append("// ============================================================")
    lines.append("// AUTO-GENERATED FILE — DO NOT EDIT DIRECTLY")
    lines.append("//")
    lines.append("// Generated by: backend/scripts/generate_frontend_enums.py")
    lines.append(f"// Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append("// Source: meta.meta_enum (PostgreSQL)")
    lines.append("//")
    lines.append("// To regenerate:")
    lines.append("//   cd backend && ./venv/bin/python scripts/generate_frontend_enums.py")
    lines.append("// ============================================================")
    lines.append("")
    
    # enum_type별로 그룹화
    grouped: dict[str, list[dict[str, Any]]] = {}
    for item in enums:
        etype = item["enum_type"]
        if etype not in grouped:
            grouped[etype] = []
        grouped[etype].append(item)
    
    # 각 enum_type별로 as const 객체 + type 생성
    for enum_type in sorted(grouped.keys()):
        values = grouped[enum_type]
        ts_const_name = enum_type.upper()  # e.g., "order_status" → "ORDER_STATUS"
        ts_type_name = _to_ts_type_name(enum_type)  # e.g., "order_status" → "OrderStatus"
        
        # 주석 (description에서 첫 번째 값의 설명을 대표로 사용)
        first_desc = values[0]["description"] if values[0]["description"] else enum_type
        lines.append(f"// {first_desc}")
        lines.append(f"export const {ts_const_name} = {{")
        
        for v in values:
            const_name = _to_ts_constant_name(v["enum_value"])
            desc = v["description"] or ""
            if desc:
                lines.append(f"  /** {desc} */")
            lines.append(f"  {const_name}: '{v['enum_value']}',")
        
        lines.append("} as const;")
        lines.append("")
        lines.append(
            f"export type {ts_type_name} = "
            f"(typeof {ts_const_name})[keyof typeof {ts_const_name}];"
        )
        lines.append("")
    
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# 4. 메인
# ---------------------------------------------------------------------------
def main() -> None:
    session = SessionLocal()
    try:
        enums = fetch_enums(session)
        if not enums:
            print("ERROR: meta.meta_enum 테이블이 비어있거나 존재하지 않습니다.")
            print("먼저 insert_meta_enums.sql을 실행해주세요.")
            sys.exit(1)
        
        ts_content = generate_ts(enums)
        
        # 출력 경로
        output_dir = os.path.join(
            _PROJECT_ROOT,
            "..",
            "workspace",
            "frontend",
            "packages",
            "domain",
            "src",
            "__generated__",
        )
        os.makedirs(output_dir, exist_ok=True)
        output_path = os.path.join(output_dir, "enums.ts")
        
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(ts_content)
        
        print(f"✅ Generated: {output_path}")
        print(f"   Total enum types: {len(set(e['enum_type'] for e in enums))}")
        print(f"   Total enum values: {len(enums)}")
    finally:
        session.close()


if __name__ == "__main__":
    main()
