"""공통 모델 패키지 초기화 파일."""

from app.database import Base
from app.models.cart import Cart, CartCoupon, CartItem, CartItemOptionSnapshot
from app.models.order import (
    OrderHeader,
    OrderItem,
    OrderStatusHistory,
    OrderPayment,
    OrderShipment,
    OrderAddressSnapshot,
    OrderCoupon,
)
from app.models.product import (
    Brand,
    Category,
    Product,
    ProductCategoryMap,
    ProductImage,
    ProductOption,
    ProductOptionValue,
    SKU,
    SKUOptionValueMap,
)
from app.models.payment import (
    Payment,
    PaymentTransaction,
    PaymentMethod,
    PaymentRefund,
    PaymentLog,
)
from app.models.inventory import (
    Inventory,
    InventoryReservation,
    InventoryTransaction,
    WarehouseStock,
    InventoryAdjustment,
)
from app.models.shipment import (
    Shipment,
    ShipmentItem,
    ShipmentTracking,
    ShipmentStatusHistory,
    Warehouse,
    ShipmentPackage,
)
from app.models.promotion import (
    Promotion,
    PromotionCondition,
    PromotionTarget,
    Coupon,
    CouponIssue,
    CouponUsage,
)
from app.models.review import (
    Review,
    ReviewRating,
    ReviewImage,
    ReviewLike,
    ReviewReport,
    ReviewComment,
    ProductReviewSummary,
)
from app.models.search import (
    SearchProductIndex,
    SearchKeyword,
    SearchAutocomplete,
    SearchSynonym,
)
from app.models.admin import (
    AdminAccount,
    AdminRole,
    AdminPermission,
    AdminRolePermissionMap,
    AdminAccountRoleMap,
    AdminMenu,
    AdminActionLog,
    AdminAccessLog,
)
from app.models.enum_meta import MetaEnum

__all__ = [
    "Base",
    "Brand",
    "Category",
    "Product",
    "ProductCategoryMap",
    "ProductImage",
    "ProductOption",
    "ProductOptionValue",
    "SKU",
    "SKUOptionValueMap",
    "Cart",
    "CartCoupon",
    "CartItem",
    "CartItemOptionSnapshot",
    "OrderHeader",
    "OrderItem",
    "OrderStatusHistory",
    "OrderPayment",
    "OrderShipment",
    "OrderAddressSnapshot",
    "OrderCoupon",
    "Payment",
    "PaymentTransaction",
    "PaymentMethod",
    "PaymentRefund",
    "PaymentLog",
    "Inventory",
    "InventoryReservation",
    "InventoryTransaction",
    "WarehouseStock",
    "InventoryAdjustment",
    "Shipment",
    "ShipmentItem",
    "ShipmentTracking",
    "ShipmentStatusHistory",
    "Warehouse",
    "ShipmentPackage",
    "Promotion",
    "PromotionCondition",
    "PromotionTarget",
    "Coupon",
    "CouponIssue",
    "CouponUsage",
    "Review",
    "ReviewRating",
    "ReviewImage",
    "ReviewLike",
    "ReviewReport",
    "ReviewComment",
    "ProductReviewSummary",
    "SearchProductIndex",
    "SearchKeyword",
    "SearchAutocomplete",
    "SearchSynonym",
    "AdminAccount",
    "AdminRole",
    "AdminPermission",
    "AdminRolePermissionMap",
    "AdminAccountRoleMap",
    "AdminMenu",
    "AdminActionLog",
    "AdminAccessLog",
    "MetaEnum",
]
